# Generated by Django 5.1.4 on 2024-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ExecutiveMember',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
