# Generated by Django 5.1.4 on 2024-12-24 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0009_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('approved', models.BooleanField(default=False)),
                ('feature', models.CharField(choices=[('bookReview', 'Book Review'), ('authorSpotlight', 'Author Spotlight'), ('childrensCorner', "Children's Corner"), ('latest', 'Latest'), ('userReview', 'User Review')], default='bookReview', max_length=50)),
            ],
        ),
    ]
