# Generated by Django 5.1.4 on 2024-12-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0010_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature',
            field=models.CharField(choices=[('academic', 'Academic'), ('taskmanagement', 'Task Management'), ('suggestions', 'Suggestions'), ('special', 'Special')], default='suggestions', max_length=50),
        ),
    ]
